### PR TITLE
Implemented Admin endpoints

### PR DESCRIPTION
**Pull request by AnaSandoval-Intersys**

### CODE REVIEW

**Comment by Spawbreaker** [comment]
Hey Ana! 

I would change the /any/orders/ to just /orders/ and merge it with /user/orders/, they're publicly accessed.
- POST
  - If the logic behind /any and /user is the same I would change the parameters it requests to optional parameters. Remember Guests are also in our Customer table, they **do** have a user_id and an auth token. 
  - I would change the parameters to:
    - An auth-token (required) (Handled by jwt) to get the user id, with it we can also fetch the cart information and with that we can get the item IDs to query the DB for the actual items.
    - Billing Information
    - Shipping Information

Don´t worry about the guest giving us their email! The front end should PUT on /customers/ their e-mail, phone, first name and last name before POSTing this request ;) 

- GET 
  - Sending the user ID would be dangerous, as someone with the right ID could see delicate information (shipping/billing address) of a user. It's better to request an Auth-token, which we can decrypt into the user's ID. 
  - I hadn't thought of sort/filter/pagination for this, but it totally makes sense! Good job. 
  - Don't worry, if a guest does this it would just return an empty json / the orders they made THIS session. So it's failproof.

Admin
  - PUT
    - I would change the help to "ID of the new status".
  - GET
    - This one's perfect
  - DELETE
    - I don't know if I would consider it missing. It is not a very common method, in fact, this information should almost never be deleted. But maybe it would be good to have it? Up to you, this one wouldn't see use anyway under normal circumstances.

**Comment by AnaSandoval-Intersys** [comment]
Hi! My endpoints are for admin management, not for orders.
I don't know if there was something wrong with the commit that might have gotten them confused? Let me know if that's the case. I'm just getting the hang of github.
I think Pablo was the one who made the one for Orders.

**Comment by Spawbreaker** [comment]
Hey Ana! 

I gave you the review I meant for /orders/ which is @pablorich 's

PUT
 - I would make first name and last name optional, no need to clutter our message for fields we may not update
POST
 - Looks great
GET
 - Do we handle filtering? Up to you
DELETE
 - Looks great 

Maybe I would change the ns to /admin/staff/ since /management/ could be ambiguous. Up to you. But kudos for not saying "admin/admin"

**Comment by AnaSandoval-Intersys** [comment]
Yeap, that's the one.
- For Put, since we always load the current name and last name when the edit view is open, I think I'd be wise to keep them as mandatory so we don't allow the user to edit and send a blank field. In case they don't change them, they'll just be send as they were.

- Not filtering, but I liked the idea of including an option to sort the admins. It could be from A-Z or from oldest, or newest.. It's an option that we didn't really explore but could be useful, especially if at some point there's a considerable amount of admins.

**Comment by Spawbreaker** [comment]
Filtering would also add a "simple" way to look someone up by matching up their name. But I feel we should only need it if we ever toss in a way to search by name anyway. Looks good to merge :D

**Pull request merged**
